$(DIR_OUT)/%.elf: $(OBJ)
	@echo "Building binary... $(APPLICATION_NAME).elf"
	$(CC) $(CFLAGS) -o $@ $(OBJ) $(LDFLAGS)
	$(SIZE) --format=avr $@
	
$(DIR_OUT)/%.lss: $(DIR_OUT)/%.elf
	@echo "Creating Extended Listing... $@"
	$(OBJDUMP) -h -S $< > $@
	
$(DIR_OUT)/%.hex: $(DIR_OUT)/%.elf
	@echo "Create Flash image (ihex format)... $@"
	$(OBJCOPY) -R .eeprom -O ihex $< $@

$(DIR_OUT)/%.bin: $(DIR_OUT)/%.elf
	@echo "Create Flash image (binary format)... $@"	
	$(OBJCOPY) -R .eeprom -O binary $< $@
	
$(DIR_OUT)/%.eep: $(DIR_OUT)/%.elf
	@echo "Create eeprom image (ihex format)... $@"
	$(OBJCOPY) -j .eeprom -O ihex $< $@