#ifndef BOOTLOADER_COMMON_PROTOCOL_H_
#define BOOTLOADER_COMMON_PROTOCOL_H_


#define IMAGE_CHECKSUM_POLYNOMIAL 0xD9 // (CRC-8-WCDMA)


typedef enum _BootloaderCommonCommand {
	BOOTLOADER_COMMON_COMMAND_CONNECT = 0xa0,
	BOOTLOADER_COMMON_COMMAND_GET_INFO,
	BOOTLOADER_COMMON_COMMAND_FLASH_READ_PAGE,
	BOOTLOADER_COMMON_COMMAND_FLASH_ERASE_PAGE,
	BOOTLOADER_COMMON_COMMAND_FLASH_WRITE_PAGE,
	BOOTLOADER_COMMON_COMMAND_E2PROM_READ,
	BOOTLOADER_COMMON_COMMAND_E2PROM_WRITE,
	BOOTLOADER_COMMON_COMMAND_REBOOT
} BootloaderCommonCommand;

typedef enum _BootloaderCommonCommandStatus {
	BOOTLOADER_COMMON_COMMAND_STATUS_OK = 0xc0,
	BOOTLOADER_COMMON_COMMAND_STATUS_ERROR
} BootloaderCommonCommandStatus;


#endif /* BOOTLOADER_COMMON_PROTOCOL_H_ */
